name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev, "feat/**"]
  workflow_dispatch:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run Spring Boot tests
        run: mvn test -Dspring.profiles.active=test
        working-directory: ./Backend
        env:
          EXTERNAL_API_KEY: ${{ secrets.CONCORDIA_API_KEY }}
          EXTERNAL_API_USER: ${{ secrets.CONCORDIA_API_USER }}

      - name: JaCoCo Coverage Report
        if: github.event_name == 'pull_request'
        uses: madrapps/jacoco-report@50d3aff4548aa991e6753342d9ba291084e63848
        with:
          paths: Backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Coverage Report for Backend"
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80

  mobile-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Install dependencies
        working-directory: ./mobile
        run: npm ci

      - name: Run lint
        working-directory: ./mobile
        run: npm run lint:ci

      - name: Run tests
        working-directory: ./mobile
        run: npx jest --coverage

      - name: Jest Coverage Report
        if: github.event_name == 'pull_request'
        uses: davelosert/vitest-coverage-report-action@15b5b41bb7d36796d89f4bf482b09529c53f3446
        with:
          name: Mobile
          json-summary-path: mobile/coverage/coverage-summary.json
          json-final-path: mobile/coverage/coverage-final.json
          vite-config-path: mobile/vitest.config.ts
          file-coverage-mode: changes
          threshold-icons: "{0: 'ðŸ”´', 75: 'ðŸŸ ', 80: 'ðŸŸ¢'}"
